### ISSUE TITLE
Schedule incorrectly displaying entries.

### ISSUE THREAD

**Issue by Beldorf** [UnderscoreNorth/Cynomystica#27]
The schedule will display shows on the wrong day, It's tied to a persons time zone. for me as a CST resident anything scheduled for between midnight and 1am will show up on the previous day. for Sieg who is on mountain time, anything from midnight to 1am his time will show up on the previous day.
I'll attach some screencaps to show what it looks like. This only started to happen after the schedule was changed to display in local time.
https://pomf2.lain.la/f/7kr8k47.png
https://pomf2.lain.la/f/tenkpyjv.png
As you can see Dosanko Gal is set for 12:30am on the 11th, but displays as on the 10th.
I have have a feeling it'll play at the right time and day, but it'll get very confusing having the display not match when it'll actually play.

**Comment by UnderscoreNorth** [comment]
Closing for now since this was regarding daylight savings changing fuckery and will wait til it becomes a problem in november or next march
